clone:
  clone:
    image: 325714046698.dkr.ecr.eu-west-1.amazonaws.com/dmx/drone-git:next
    pull: true

pipeline:
  pypi_login:
    group: auth
    image: 325714046698.dkr.ecr.eu-west-1.amazonaws.com/dmx/artifactory-cli-login
    pull: true
    type: pip
    output: ./pip.conf
    secrets:
      - ARTIFACTORY_USER
      - ARTIFACTORY_PASSWORD

  run_tests:
    image: 325714046698.dkr.ecr.eu-west-1.amazonaws.com/skyscanner/python-3.6-build:1.1.20
    pull: true
    environment:
      - PIP_CACHE_DIR=/drone/.pip-cache
      - PIP_CONFIG_FILE=pip.conf
    commands:
      - pip install flake8 mypy
      - flake8
      - mypy airflow tests

  build_assets:
    image: 325714046698.dkr.ecr.eu-west-1.amazonaws.com/skyscanner/python-3.6-build:1.1.20
    pull: true
    environment:
      - PIP_CACHE_DIR=/drone/.pip-cache
      - PIP_CONFIG_FILE=pip.conf
    commands:
      - python setup.py compile_assets

  pypi:
    image: 325714046698.dkr.ecr.eu-west-1.amazonaws.com/drone-plugins/drone-pypi
    repository: https://artifactory.skyscannertools.net/artifactory/api/pypi/pypi
    distributions: sdist bdist_wheel
    secrets:
      - source: ARTIFACTORY_USER
        target: username
      - source: ARTIFACTORY_PASSWORD
        target: password
    when:
      event: tag
